'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace CellAppearanceCustomization


    Partial Public Class DefaultForm

        ''' <summary>
        ''' form1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        ''' <summary>
        ''' cbApplyCustomCellAppearance control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected cbApplyCustomCellAppearance As Global.DevExpress.Web.ASPxCheckBox

        ''' <summary>
        ''' cbTopAlignRowFieldValues control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected cbTopAlignRowFieldValues As Global.DevExpress.Web.ASPxCheckBox

        ''' <summary>
        ''' pivotGrid control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected pivotGrid As Global.DevExpress.Web.ASPxPivotGrid.ASPxPivotGrid

        ''' <summary>
        ''' fieldCompanyName control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected fieldCompanyName As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

        ''' <summary>
        ''' fieldOrderDate control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected fieldOrderDate As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

        ''' <summary>
        ''' fieldProductAmount control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected fieldProductAmount As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

        ''' <summary>
        ''' fieldProductName control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected fieldProductName As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

        ''' <summary>
        ''' CustomerReportDataSource control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected CustomerReportDataSource As Global.System.Web.UI.WebControls.AccessDataSource
    End Class
End Namespace
